### ISSUE TITLE
[1.12] Crash on World load

### ISSUE THREAD

**Issue by MasterEnderman** [Wyn-Price/betterunderground#2]
Better Underground: 1.0.6
Forge: 14.23.1.2562
Crash Report: https://pastebin.com/8r66C3xr
My Config: https://pastebin.com/8PY1HgkH

**Comment by Wyn-Price** [comment]
OK i see why this is happening. This is an old mod I made a while ago before I really knew what I was doing, but I fix this now, new version out either today or tommorow

**Comment by MasterEnderman** [comment]
perfect!

Thank you for the quick response!

Could you add an option to remove the arrow drop from the bone pile block?

**Comment by Wyn-Price** [comment]
Sure!

**Comment by Wyn-Price** [comment]
I uploaded the version about an hour ago, but it hasnt been accepted. I also uploaded a version to a diffrent mod around 5 hours ago, and that hasnt been accepeted yet so Im not sure how long itll take. As soon as its done itll be on the curseforge page
