### ISSUE TITLE
Stalactite: Silk Touch Drop Bug

### ISSUE THREAD

**Issue by ghost** [Wyn-Price/betterunderground#3]
it also drops cobblestone/sandstone when silk touched. so infinite cobblestone/sandstone with 1 stalactite...
and second thing, sometimes 2x itself when silk touched. (random)
for example breaking stone stalactite with silk touch gives 2x stone stalactite + 2x cobblestone, sometimes.

**Comment by ghost** [comment]
i tried many things but couldnt fix it... how stupid i am... it dropped cobblestone everytime or no drop without silk touch, really couldnt fix xD

**Comment by Wyn-Price** [comment]
I can fix this soon
