### ISSUE TITLE
Mossy Dirt Texture

### ISSUE THREAD

**Issue by ddelaparte** [Wyn-Price/betterunderground#6]
Not a huge fan of the 32x32 texture for mossy dirt. I prefer my mods to use vanilla resolutions of 16x16 with the option to apply a resource pack.

If I produced a suitable 16x16 texture would you be willing to use it?

Barring that, can we instead / also get an option to disable its generation?

**Comment by Wyn-Price** [comment]
Uhh if you want to make a new texture go for it. Regarding generation, ive kinda left this mod, but if ill add it to my ever-expanding todo list

**Comment by ghost** [comment]
xD lol... it's just a mossy dirt, drops dirt and some vines... even generates about 1 in 1 chunk, underground. why is this so important/problem for you? you can patch the texture with vanilla dirt. create a new folder called betterunderground in assets folder in your resource pack, create textures, blocks in it, then put the vanilla dirt texture then rename it to mossydirt.png. thats all
